# -*- coding: utf-8 -*-
"""Creating a whether Application.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NTwyBn-NJ2k85zvv6m4ZNk5Q9OI96nn7
"""

!pip install requests

import requests
import json

import requests

def get_weather(city):
    base_url = "https://api.openweathermap.org/data/2.5/weather"
    api_key = "8dcbd44e1ac19040ef7c31cc5f9f8cf1"  # Replace with your OpenWeatherMap API key
    params = {"q": city, "appid": api_key, "units": "metric"}  # Adjust units as needed
    try:
        response = requests.get(base_url, params=params)
        response.raise_for_status()  # Raise an exception for HTTP errors
        data = response.json()
        return data
    except requests.exceptions.RequestException as e:
        print(f"Error: {e}")
        return None

def display_weather(weather_data):
    if weather_data:
        print(f"Weather in {weather_data['name']}, {weather_data['sys']['country']}:")
        print(f"Temperature: {weather_data['main']['temp']}°C")
        print(f"Description: {weather_data['weather'][0]['description']}")
        print(f"Humidity: {weather_data['main']['humidity']}%")
        print(f"Wind Speed: {weather_data['wind']['speed']} m/s")
    else:
        print("Failed to retrieve weather data.")

city = input("Enter a city: ")
weather_data = get_weather(city)
display_weather(weather_data)

